apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testwebapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testwebapp
    spec:
      containers:
        - name: testwebapp
          image: docker.io/mcywka/testwebapplication:version1.99
          ports:
            - containerPort: 80
          env:
            - name: Hello
              value: "Hello from docker"