apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testwebapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: testwebapp
    spec:
      containers:
      - name: testwebapp
        image: docker.io/mcywka/testwebapplication:version-0.1.2
        ports:
        - containerPort: 80
        env:
          - name: Hello
            value: "Hello from docker"