apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testwebapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: testwebapp
    spec:
      containers:
      - name: testwebapp
        image: docker.io/mcywka/testwebapplication:version-0.2.0
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_DIR
            value: /usr/db
          - name: Hello
            value: "Hello from docker"
        volumeMounts:               # 3
        - name: sqlite-volume       # 3.a
          mountPath: /usr/db        # 3.b
      volumes:
        - name: sqlite-volume         # 2
          persistentVolumeClaim:
            claimName: sqlite-pvc     # 1 