apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helmtestwebapp.fullname" . }}-azure-file-claim
  labels:
{{ include "helmtestwebapp.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi